name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
        
    - name: Update paper list
      run: |
        cd iptvm3u8
        cat 3.m3u
        python 2.py
        cat 3.m3u
        
    - name: commit
      run: |
        git config --global user.email wymanhns@gmail.com
        git config --global user.name wymanhns
        git add .
        git commit -m "first commit" 
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
